# Generated by Django 4.0.5 on 2022-06-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospital_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='static/images'),
        ),
    ]
