# Generated by Django 3.0.5 on 2022-07-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
    ]
